### ISSUE TITLE
Tests broken after latest changes

### ISSUE THREAD

**Issue by jajik** [modcluster/mod_proxy_cluster#124] opened 2023-08-07 10:22 UTC
The tests are now broken after one of the [latest changes](https://github.com/modcluster/mod_cluster/commit/b56a61883e9eb885320c3ab92b15e68826070f6c) in mod_cluster (Java part).

The issue is a different handling of app states that for jsp only apps results in apps not being propagated towards the httpd.

The best solution I came up with seems to be after uploading the app to execute something like:

```
curl localhost:6666 -H "User-Agent: ClusterListener/1.0" -X ENABLE-APP --data "JVMRoute=${node}&Alias=localhost&Context=%2F${context}"
```

**Comment by jajik** [comment] 2023-08-07 10:42
It's sufficient to use `basetests.sh` from the new testsuite. Basically:

1) run httpd with mod_proxy_cluster
2) run tomcat with mod_cluster
3) copy testapp to webapps
i) curl on tomcat directly is ok
ii) curl via httpd is not (404)
iii) if you run the curl with ENABLE-APP as described above, ii) is ok

The change in behaviour was caused by the commit linked in the first message.

**Comment by rhusar** [comment] 2023-08-07 15:08
Anyway, the clusterbench also has a JSP page and nevertheless, JSP compiles into a Servlet anwyay, so that's not exactly the culprit. I am wondering if we are missing some event being observed from container integration that @jajik is triggering.

**Comment by jajik** [comment] 2023-08-08 06:24
Interesting you can't reproduce. I ran into it because of my other PR with CI stopped working (tests started failing), you can see it here

* https://github.com/jajik/mod_proxy_cluster/actions/runs/5761718108 (commit https://github.com/modcluster/mod_cluster/commit/e36824dd77a49dbceac6e1f72b904527f545ca6a OK)
* https://github.com/jajik/mod_proxy_cluster/actions/runs/5761793638 (commit https://github.com/modcluster/mod_cluster/commit/b56a61883e9eb885320c3ab92b15e68826070f6c NOK)
* https://github.com/jajik/mod_proxy_cluster/actions/runs/5761865898 (commit https://github.com/modcluster/mod_cluster/commit/e57e31c34bf8857c090fd5ceef492aa779165861 OK)

With that said, I made a mess in the CI PR, so I'm going to clean it and try again.

**Comment by rhusar** [comment] 2023-08-09 09:12
While debugging, I have noticed the main difference is that the server is reconfigured to use 'autoDeploy' which is disabled by default which would be nice to mention in the report 👍🏼 

```
      <Host name="localhost"  appBase="webapps"
            unpackWARs="true" autoDeploy="true">
```

**Comment by rhusar** [comment] 2023-08-09 10:01
Just to mention, using immutable containers with dynamic deploy is a really funny antipattern :-D but sure, it's a testsuite.

**Comment by jajik** [comment] 2023-08-09 10:10
> While debugging, I have noticed the main difference is that the server is reconfigured to use 'autoDeploy' which is disabled by default which would be nice to mention in the report 👍🏼
> 
> ```
>       <Host name="localhost"  appBase="webapps"
>             unpackWARs="true" autoDeploy="true">
> ```

That's not something that changed in the meantime so it did not occur to me to mention the whole config.

> Just to mention, using immutable containers with dynamic deploy is a really funny antipattern :-D but sure, it's a testsuite, anything goes.

It confused me at first as well, but that will change once #126 is done.

> I see the events being called correctly in the TomcatEventHandlerAdapter eventually getting to Context#start(..), so still not clear what's the problem.

Hmm, were you able to reproduce it?

**Comment by rhusar** [comment] 2023-08-09 22:33
I was able to reproduce it now since I noticed that the test is still using old Tomcat 8.5 - I was testing with 10.1.

What I am not seeing happen on tomcat 8.5 is call to org.jboss.modcluster.container.tomcat.TomcatEventHandlerAdapter#containerEvent when using the automatic deploy.

**Comment by jajik** [comment] 2023-08-10 06:37
Interesting, I tried 10.1 image and it seemed to behave the same. I'll retry it for sure.

**Comment by rhusar** [comment] 2023-08-10 11:06
> I was able to reproduce it now since I noticed that the test is still using old Tomcat 8.5 - I was testing with 10.1.
> 
> What I am not seeing happen on tomcat 8.5 is call to org.jboss.modcluster.container.tomcat.TomcatEventHandlerAdapter#containerEvent when using the automatic deploy.

Tracker with the fix https://issues.redhat.com/browse/MODCLUSTER-797.

**Comment by rhusar** [comment] 2023-08-10 16:00
> > I was able to reproduce it now since I noticed that the test is still using old Tomcat 8.5 - I was testing with 10.1.
> > What I am not seeing happen on tomcat 8.5 is call to org.jboss.modcluster.container.tomcat.TomcatEventHandlerAdapter#containerEvent when using the automatic deploy.
> 
> Tracker with the fix https://issues.redhat.com/browse/MODCLUSTER-797.

Fixed by https://github.com/modcluster/mod_proxy_cluster/pull/135 - closing.

**Closed by rhusar** 2023-08-10 16:00 UTC
