### ISSUE TITLE
failed to build on RHEL 8,7

### ISSUE THREAD

**Issue by DarthLED** [modcluster/mod_proxy_cluster#86] opened 2023-05-22 08:53 UTC
Hi All,

I have tried to cmake on RHEL with following error. I am quite new to this and failed to resolve with my own efforts.
Could anyone please help me on this? Thank you and have a nice day.

```
[  5%] Building C object mod_proxy_cluster/CMakeFiles/mod_proxy_cluster.dir/mod_proxy_cluster.c.o
/home/user00/mod_proxy_cluster/native/mod_proxy_cluster/mod_proxy_cluster.c: In function ‘proxy_cluster_trans’:
/home/user00/mod_proxy_cluster/native/mod_proxy_cluster/mod_proxy_cluster.c:2693:46: error: ‘PROXYPASS_MAP_ENCODED’ undeclared (first use in this function); did you mean ‘PROXYPASS_NOCANON’?
             int enc = (dconf->alias->flags & PROXYPASS_MAP_ENCODED) != 0;
                                              ^~~~~~~~~~~~~~~~~~~~~
                                              PROXYPASS_NOCANON
/home/user00/mod_proxy_cluster/native/mod_proxy_cluster/mod_proxy_cluster.c:2693:46: note: each undeclared identifier is reported only once for each function it appears in
/home/user00/mod_proxy_cluster/native/mod_proxy_cluster/mod_proxy_cluster.c: In function ‘proxy_cluster_hooks’:
/home/user00/mod_proxy_cluster/native/mod_proxy_cluster/mod_proxy_cluster.c:3537:5: warning: implicit declaration of function ‘ap_hook_child_stopping’; did you mean ‘ap_hook_child_status’? [-Wimplicit-function-declaration]
     ap_hook_child_stopping(proxy_cluster_child_stopping, NULL, NULL, APR_HOOK_MIDDLE);
     ^~~~~~~~~~~~~~~~~~~~~~
     ap_hook_child_status
make[2]: *** [mod_proxy_cluster/CMakeFiles/mod_proxy_cluster.dir/build.make:76: mod_proxy_cluster/CMakeFiles/mod_proxy_cluster.dir/mod_proxy_cluster.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:170: mod_proxy_cluster/CMakeFiles/mod_proxy_cluster.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

```

**Comment by jajik** [comment] 2023-05-24 09:43
Hello,

could you share the whole output?

Do you have httpd locally available? The macro comes from `mod_proxy.h` where it's defined.

**Comment by jajik** [comment] 2023-05-24 11:09
Ok, so I can confirm the same behaviour on RHEL 8.6. This is due to older httpd version available in its repositories – 2.4.37 if I am not mistaken.

The macro above was introduced in a later version (2.4.49) [here](https://github.com/apache/httpd/commit/b11eb1d7a34b36c60a8ca2c7c9c0a0a2f7b4d448).

**Comment by DarthLED** [comment] 2023-05-25 08:59
Thanks for the update
lemme try newer httpd version

**Comment by jfclere** [comment] 2023-05-25 12:53
well a 1.3.18 Final as we haven't tag any Final in mod_proxy_cluster 2.x

**Comment by jajik** [comment] 2023-05-30 07:15
Hi @DarthLED, any update on this, were you successful using a newer version[^1]? Can we close this issue?

[^1]:  Supported versions are 2.4.53 and newer, docs were updated to reflect that.

**Comment by jajik** [comment] 2023-06-13 11:06
Closing as there is no activity for two weeks.

**Closed by jajik** 2023-06-13 11:06 UTC
Labels: help wanted
